### ISSUE TITLE
Close Menu on selection

### ISSUE THREAD

**Issue by Alan-Penkar** [Codebrahma/react-responsive-multi-level-menu#1]
I'll admit this may be a silly comment - I'm fairly new to modern frontend development.  I was expecting this to close when a leaf node was selected and it remains open - how can I change this behavior to close when I have selected an item?

**Comment by ashwinKumar0505** [comment]
Hai @Alan-Penkar . You can make use of closeMenu callback which comes with the onClick prop for the menubar. Please refer the codesandbox link for the example.

https://codesandbox.io/s/quizzical-cdn-yg0bu?file=/src/App.js
